.TH "_BlockLMS" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_BlockLMS \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCXB\fP \fBsignal\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBdelay_line\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBy\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBXhat\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBWhat\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBY\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBYhat\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBerror\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBErrhat\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBUpdate\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBupdate\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBadaptation_rate\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBleak_rate\fP"
.br
.ti -1c
.RI "int \fBfilter_type\fP"
.br
.ti -1c
.RI "fftwf_plan \fBXplan\fP"
.br
.ti -1c
.RI "fftwf_plan \fBYplan\fP"
.br
.ti -1c
.RI "fftwf_plan \fBWplan\fP"
.br
.ti -1c
.RI "fftwf_plan \fBErrhatplan\fP"
.br
.ti -1c
.RI "fftwf_plan \fBUPDplan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file lmadf.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
