.TH "_cmd_tbl_entry" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_cmd_tbl_entry \- 
.SH SYNOPSIS
.br
.PP
\fC#include </usr/home/larry/projects/DttSp/dttsp-ng/src/thunk.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBkey\fP"
.br
.ti -1c
.RI "Thunk \fBthk\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Command table 
.PP
Definition at line 10 of file thunk.h.
.SH "Field Documentation"
.PP 
.SS "char* \fB_cmd_tbl_entry::key\fP"
.PP
Table key 
.PP
Definition at line 12 of file thunk.h.
.PP
Referenced by Thunk_lookup().
.SS "Thunk \fB_cmd_tbl_entry::thk\fP"
.PP
Function pointer 
.PP
Definition at line 13 of file thunk.h.
.PP
Referenced by Thunk_lookup().

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
