.TH "_dcblocker" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_dcblocker \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBlev\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBbuf\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBinp\fP [BLKMEM]"
.br
.ti -1c
.RI "\fBREAL\fP \fBout\fP [BLKMEM]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 56 of file dcblock.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
