.TH "_dttspagc" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_dttspagc \- 
.SH SYNOPSIS
.br
.PP
\fC#include </usr/home/larry/projects/DttSp/dttsp-ng/src/dttspagc.h>\fP
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBfasthang\fP"
.br
.ti -1c
.RI "int \fBfastindx\fP"
.br
.ti -1c
.RI "int \fBhangindex\fP"
.br
.ti -1c
.RI "int \fBindx\fP"
.br
.ti -1c
.RI "int \fBmask\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBsndx\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBattack\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBdecay\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBfastattack\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBfastdecay\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBfasthangtime\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBhangthresh\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBhangtime\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBone_m_attack\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBone_m_decay\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBone_m_fastattack\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBone_m_fastdecay\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBsamprate\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBslope\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBcirc\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBbuff\fP"
.br
.ti -1c
.RI "char \fBtag\fP [4]"
.br
.ti -1c
.RI "\fBREAL\fP \fBbottom\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBfastnow\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBfix\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBlimit\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBnow\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBold\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBraw\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBtop\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
AGC control 
.PP
Definition at line 58 of file dttspagc.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
