.TH "_eq" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_eq \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCXB\fP \fBdata\fP"
.br
.ti -1c
.RI "\fBFiltOvSv\fP \fBp\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBin\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBout\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBnum\fP [9]"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBden\fP [6]"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBnotchflag\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 65 of file graphiceq.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
