.TH "_filt_ov_sav" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_filt_ov_sav \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBbuflen\fP"
.br
.ti -1c
.RI "int \fBfftlen\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBzfvec\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBzivec\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBzovec\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBzrvec\fP"
.br
.ti -1c
.RI "fftwf_plan \fBpfwd\fP"
.br
.ti -1c
.RI "fftwf_plan \fBpinv\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBscale\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file ovsv.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
