.TH "_fm_demod" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_fm_demod \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBibuf\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBobuf\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBlock\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBafc\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBcvt\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBalpha\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBbeta\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBf\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBl\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBh\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBphs\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBdelay\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 51 of file fm_demod.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
