.TH "_iqstate" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_iqstate \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBREAL\fP \fBphase\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBgain\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 47 of file correctIQ.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
