.TH "_ISOband_t" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_ISOband_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBREAL\fP \fBnominal\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBexact\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBlow\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBhigh\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 39 of file isoband.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
