.TH "_keyer_state" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_keyer_state \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdebounce\fP"
.br
.ti -1c
.RI "int \fBmode\fP"
.br
.ti -1c
.RI "int \fBweight\fP"
.br
.ti -1c
.RI "double \fBwpm\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBwpm\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBiambic\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBmdlmdB\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBrevpdl\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBdit\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBdah\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBkhar\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBword\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 73 of file iambic-keyer.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
