.TH "_keyer_logic" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_keyer_logic \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdlay_type\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBinit\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBdit\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBdah\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBaltrn\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBpsqam\fP"
.br
.ti -1c
.RI "int \fBcurr\fP"
.br
.ti -1c
.RI "int \fBiamb\fP"
.br
.ti -1c
.RI "int \fBlast\fP"
.br
.ti -1c
.RI "double \fBbeep\fP"
.br
.ti -1c
.RI "double \fBdlay\fP"
.br
.ti -1c
.RI "double \fBelem\fP"
.br
.ti -1c
.RI "double \fBmidl\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBinvtd\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBbeep\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBdlay\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBelem\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBmidl\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 102 of file iambic-keyer.c.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
