.TH "_meter_block" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_meter_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBOOLEAN\fP \fBflag\fP"
.br
.ti -1c
.RI "int \fBlabel\fP"
.br
.ti -1c
.RI "int \fBlast\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBval\fP [MAXRX][RXMETERPTS]"
.br
.ti -1c
.RI "RXMETERTYPE \fBmode\fP [MAXRX]"
.br
.ti -1c
.RI "TXMETERTYPE \fBmode\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBrx\fP [MAXRX][RXMETERPTS]"
.br
.ti -1c
.RI "\fBREAL\fP \fBtx\fP [TXMETERPTS]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 108 of file meter.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
