.TH "_nbstate" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_nbstate \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCXB\fP \fBsigbuf\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBaverage_mag\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBthreshold\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBaverage_sig\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBdelay\fP [8]"
.br
.ti -1c
.RI "int \fBdelayindex\fP"
.br
.ti -1c
.RI "int \fBsigindex\fP"
.br
.ti -1c
.RI "int \fBhangtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 41 of file noiseblanker.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
