.TH "_oscillator" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_oscillator \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "void * \fBsignalpoints\fP"
.br
.ti -1c
.RI "double \fBPhase\fP"
.br
.ti -1c
.RI "double \fBFrequency\fP"
.br
.ti -1c
.RI "OscType \fBOscillatorType\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 48 of file oscillator.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
