.TH "_speechprocessor" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_speechprocessor \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "\fBRLB\fP \fBCG\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBSpeechProcessorBuffer\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBLastCG\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBK\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBMaxGain\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBfac\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file speechproc.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
