.TH "_spec_block" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_spec_block \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBBOOLEAN\fP \fBflag\fP"
.br
.ti -1c
.RI "\fBBOOLEAN\fP \fBpolyphase\fP"
.br
.ti -1c
.RI "Windowtype \fBwintype\fP"
.br
.ti -1c
.RI "int \fBbuflen\fP"
.br
.ti -1c
.RI "int \fBfill\fP"
.br
.ti -1c
.RI "int \fBlabel\fP"
.br
.ti -1c
.RI "int \fBlast\fP"
.br
.ti -1c
.RI "int \fBmask\fP"
.br
.ti -1c
.RI "int \fBplanbits\fP"
.br
.ti -1c
.RI "int \fBrxk\fP"
.br
.ti -1c
.RI "int \fBscale\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBaccum\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBtimebuf\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBfreqbuf\fP"
.br
.ti -1c
.RI "\fBREAL\fP * \fBoutput\fP"
.br
.ti -1c
.RI "\fBREAL\fP * \fBoscope\fP"
.br
.ti -1c
.RI "\fBREAL\fP * \fBwindow\fP"
.br
.ti -1c
.RI "fftwf_plan \fBplan\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 62 of file spectrum.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
