.TH "_spot_tone_gen" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_spot_tone_gen \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBREAL\fP \fBcurr\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBgain\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBmul\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBscl\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBsr\fP"
.br
.ti -1c
.RI "int \fBsize\fP"
.br
.ti -1c
.RI "int \fBstage\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBbuf\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBfreq\fP"
.br
.ti -1c
.RI "\fBOSC\fP \fBgen\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBdur\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBincr\fP"
.br
.ti -1c
.RI "int \fBwant\fP"
.br
.ti -1c
.RI "int \fBhave\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 53 of file spottone.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
