.TH "_wscompander" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
_wscompander \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBnpts\fP"
.br
.ti -1c
.RI "int \fBnend\fP"
.br
.ti -1c
.RI "\fBREAL\fP \fBfac\fP"
.br
.ti -1c
.RI "\fBREAL\fP * \fBtbl\fP"
.br
.ti -1c
.RI "\fBCXB\fP \fBbuff\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file wscompand.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
