.TH "am_demod.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
am_demod.h \- AM demodulator defines. 
.SH SYNOPSIS
.br
.PP
\fC#include <fromsys.h>\fP
.br
\fC#include <banal.h>\fP
.br
\fC#include <splitfields.h>\fP
.br
\fC#include <datatypes.h>\fP
.br
\fC#include <bufvec.h>\fP
.br
\fC#include <cxops.h>\fP
.br
\fC#include <fastrig.h>\fP
.br
\fC#include <update.h>\fP
.br
\fC#include <lmadf.h>\fP
.br
\fC#include <fftw3.h>\fP
.br
\fC#include <ovsv.h>\fP
.br
\fC#include <filter.h>\fP
.br
\fC#include <oscillator.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_am_demod\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBTWOPI\fP   (2.0*M_PI)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef enum \fB_ammode\fP \fBAMMode\fP"
.br
.ti -1c
.RI "typedef \fB_am_demod\fP \fBAMDDesc\fP"
.br
.ti -1c
.RI "typedef \fB_am_demod\fP * \fBAMD\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fB_ammode\fP { \fBAMdet\fP, \fBSAMdet\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBAMDemod\fP (\fBAMD\fP am)"
.br
.ti -1c
.RI "\fBAMD\fP \fBnewAMD\fP (\fBREAL\fP samprate, \fBREAL\fP f_initial, \fBREAL\fP f_lobound, \fBREAL\fP f_hibound, \fBREAL\fP f_bandwid, int size, \fBCOMPLEX\fP *ivec, \fBCOMPLEX\fP *ovec, \fBAMMode\fP mode, char *tag)"
.br
.ti -1c
.RI "void \fBdelAMD\fP (\fBAMD\fP am)"
.br
.in -1c
.SH "Detailed Description"
.PP 
AM demodulator defines. 

This file is part of a program that implements a Software-Defined Radio.
.PP
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
The authors can be reached by email at
.PP
\fBAuthor:\fP
.RS 4
ab2kt@arrl.net or 
.PP
rwmcgwier@comcast.net
.RE
.PP
or by paper mail at
.PP
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807 
.PP
Definition in file \fBam_demod.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define TWOPI   (2.0*M_PI)"
.PP
Constant (2 * Pi) 
.PP
Definition at line 117 of file am_demod.h.
.PP
Referenced by init_pll(), pll(), and setup_tx().
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_am_demod\fP * \fBAMD\fP"
.PP
AM demod data 
.SS "typedef struct \fB_am_demod\fP  \fBAMDDesc\fP"
.PP
AM demod data 
.SS "typedef enum \fB_ammode\fP  \fBAMMode\fP"
.PP
AM demod mode 
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fB_ammode\fP"
.PP
AM demod mode 
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIAMdet \fP\fP
Normal AM 
.TP
\fB\fISAMdet \fP\fP
Synchronous AM 
.PP
Definition at line 55 of file am_demod.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
