bufvec.c
NAME
bufvec.c - Creation, deletion, management for vectors and buffers.
SYNOPSIS
#include <bufvec.h>
#include <fftw3.h>
Functions
char * safealloc (int count, int nbytes, char *tag)
void safefree (char *p)
size_t safememcurrcount (void)
void safememreset (void)
REAL * newvec_REAL (int size, char *tag)
void delvec_REAL (REAL *vec)
IMAG * newvec_IMAG (int size, char *tag)
void delvec_IMAG (IMAG *vec)
COMPLEX * newvec_COMPLEX (int size, char *tag)
void delvec_COMPLEX (COMPLEX *vec)
COMPLEX * newvec_COMPLEX_fftw (int size, char *tag)
void delvec_COMPLEX_fftw (COMPLEX *vec)
CXB newCXB (int size, COMPLEX *base, char *tag)
void delCXB (CXB p)
RLB newRLB (int size, REAL *base, char *tag)
void delRLB (RLB p)
REAL normalize_vec_REAL (REAL *v, int n)
REAL normalize_vec_COMPLEX (COMPLEX *z, int n)
void dump_REAL (FILE *fp, char *head, REAL *ptr, int beg, int fin)
void dump_IMAG (FILE *fp, char *head, IMAG *ptr, int beg, int fin)
void dump_CX (FILE *fp, char *head, COMPLEX *ptr, int beg, int fin)
Variables
PRIVATE size_t _safemem_currcount = 0
Detailed Description
Creation, deletion, management for vectors and buffers.
This file is part of a program that implements a Software-Defined Radio.
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
The authors can be reached by email at
Author:
ab2kt@arrl.net or
rwmcgwier@comcast.net
or by paper mail at
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807
Definition in file bufvec.c.
Function Documentation
char* safealloc (int count, int nbytes, char * tag)
Wrapper around calloc()
Definition at line 48 of file bufvec.c.
References _safemem_currcount.
Referenced by create_globals(), new_blms(), new_lmsr(), newAMD(), newCorrectIQ(), newCWToneGen(), newCXB(), newDCBlocker(), newDttSPAgc(), newFIR_COMPLEX(), newFIR_REAL(), newFMD(), newRLB(), newvec_COMPLEX(), newvec_IMAG(), newvec_REAL(), and setup_local_audio().
void safefree (char * p)
Wrapper around free()
Definition at line 67 of file bufvec.c.
Referenced by closeup(), del_blms(), del_lmsr(), delAMD(), delCorrectIQ(), delCWToneGen(), delCXB(), delDCBlocker(), delDttSPAgc(), delFIR_COMPLEX(), delFIR_REAL(), delFMD(), delRLB(), delvec_COMPLEX(), delvec_IMAG(), delvec_REAL(), destroy_globals(), and reset_for_buflen().
size_t safememcurrcount (void)
Get reference counters
Definition at line 74 of file bufvec.c.
References _safemem_currcount.
void safememreset (void)
Reset reference counters
Definition at line 80 of file bufvec.c.
References _safemem_currcount.
Referenced by reset_for_buflen(), and setup().
Author
Generated automatically by Doxygen for DttSp from the source code.