bufvec.h
NAME
bufvec.h - Definitions for vector and buffer data structures and utilities.
SYNOPSIS
#include <fromsys.h>
#include <datatypes.h>
#include <complex.h>
#include <cxops.h>
Data Structures
struct _complex_buffer_desc
struct _real_buffer_desc
Defines
#define CXBbase(p) ((p)->data)
#define CXBdata(p, i) (CXBbase(p)[(i)])
#define CXBreal(p, i) (CXBbase(p)[(i)].re)
#define CXBimag(p, i) (CXBbase(p)[(i)].im)
#define CXBsize(p) ((p)->size)
#define CXBovlp(p) ((p)->ovlp)
#define CXBwant(p) ((p)->want)
#define CXBhave(p) ((p)->have)
#define CXBdone(p) ((p)->done)
#define CXBmine(p) ((p)->mine)
#define RLBbase(p) ((p)->data)
#define RLBdata(p, i) (RLBbase(p)[(i)])
#define RLBsize(p) ((p)->size)
#define RLBovlp(p) ((p)->ovlp)
#define RLBwant(p) ((p)->want)
#define RLBhave(p) ((p)->have)
#define RLBdone(p) ((p)->done)
#define RLBmine(p) ((p)->mine)
Typedefs
typedef _complex_buffer_desc CXBuffer
typedef _complex_buffer_desc * CXB
typedef _real_buffer_desc RLBuffer
typedef _real_buffer_desc * RLB
Functions
char * safealloc (int count, int nbytes, char *tag)
void safefree (char *p)
size_t safememcurrcount (void)
void safememreset (void)
REAL * newvec_REAL (int size, char *tag)
void delvec_REAL (REAL *vec)
IMAG * newvec_IMAG (int size, char *tag)
void delvec_IMAG (IMAG *vec)
COMPLEX * newvec_COMPLEX (int size, char *tag)
void delvec_COMPLEX (COMPLEX *buf)
COMPLEX * newvec_COMPLEX_fftw (int size, char *tag)
void delvec_COMPLEX_fftw (COMPLEX *buf)
void dump_REAL (FILE *fp, char *head, REAL *ptr, int beg, int fin)
void dump_IMAG (FILE *fp, char *head, IMAG *ptr, int beg, int fin)
void dump_CX (FILE *fp, char *head, COMPLEX *ptr, int beg, int fin)
CXB newCXB (int size, COMPLEX *base, char *tag)
void delCXB (CXB p)
RLB newRLB (int size, REAL *base, char *tag)
void delRLB (RLB p)
REAL normalize_vec_REAL (REAL *, int)
REAL normalize_vec_COMPLEX (COMPLEX *, int)
Detailed Description
Definitions for vector and buffer data structures and utilities.
This file is part of a program that implements a Software-Defined Radio.
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
The authors can be reached by email at
Author:
ab2kt@arrl.net or
rwmcgwier@comcast.net
or by paper mail at
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807
Definition in file bufvec.h.
Typedef Documentation
typedef struct _complex_buffer_desc * CXB
Complex data buffer
typedef struct _complex_buffer_desc CXBuffer
Complex data buffer
typedef struct _real_buffer_desc * RLB
Real data buffer
typedef struct _real_buffer_desc RLBuffer
Real data buffer
Function Documentation
char* safealloc (int count, int nbytes, char * tag)
Wrapper around calloc()
Definition at line 48 of file bufvec.c.
References _safemem_currcount.
Referenced by create_globals(), new_blms(), new_lmsr(), newAMD(), newCorrectIQ(), newCWToneGen(), newCXB(), newDCBlocker(), newDttSPAgc(), newFIR_COMPLEX(), newFIR_REAL(), newFMD(), newRLB(), newvec_COMPLEX(), newvec_IMAG(), newvec_REAL(), and setup_local_audio().
void safefree (char * p)
Wrapper around free()
Definition at line 67 of file bufvec.c.
Referenced by closeup(), del_blms(), del_lmsr(), delAMD(), delCorrectIQ(), delCWToneGen(), delCXB(), delDCBlocker(), delDttSPAgc(), delFIR_COMPLEX(), delFIR_REAL(), delFMD(), delRLB(), delvec_COMPLEX(), delvec_IMAG(), delvec_REAL(), destroy_globals(), and reset_for_buflen().
size_t safememcurrcount (void)
Get reference counters
Definition at line 74 of file bufvec.c.
References _safemem_currcount.
void safememreset (void)
Reset reference counters
Definition at line 80 of file bufvec.c.
References _safemem_currcount.
Referenced by reset_for_buflen(), and setup().
Author
Generated automatically by Doxygen for DttSp from the source code.