.TH "common.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
common.h \- A simple way to get all the necessary includes. 
.SH SYNOPSIS
.br
.PP
\fC#include <fromsys.h>\fP
.br
\fC#include <defs.h>\fP
.br
\fC#include <banal.h>\fP
.br
\fC#include <splitfields.h>\fP
.br
\fC#include <datatypes.h>\fP
.br
\fC#include <bufvec.h>\fP
.br
\fC#include <cxops.h>\fP
.br
\fC#include <ringb.h>\fP
.br
\fC#include <fftw3.h>\fP
.br
\fC#include <window.h>\fP
.br
\fC#include <ovsv.h>\fP
.br
\fC#include <filter.h>\fP
.br
\fC#include <oscillator.h>\fP
.br
\fC#include <lmadf.h>\fP
.br
\fC#include <dttspagc.h>\fP
.br
\fC#include <am_demod.h>\fP
.br
\fC#include <fm_demod.h>\fP
.br
\fC#include <resample.h>\fP
.br
\fC#include <noiseblanker.h>\fP
.br
\fC#include <correctIQ.h>\fP
.br
\fC#include <dcblock.h>\fP
.br
\fC#include <graphiceq.h>\fP
.br
\fC#include <speechproc.h>\fP
.br
\fC#include <wscompand.h>\fP
.br
\fC#include <spottone.h>\fP
.br
\fC#include <cwtones.h>\fP
.br
\fC#include <update.h>\fP
.br
\fC#include <meter.h>\fP
.br
\fC#include <spectrum.h>\fP
.br
\fC#include <isoband.h>\fP
.br
\fC#include <sdrexport.h>\fP
.br
\fC#include <local.h>\fP
.br

.SH "Detailed Description"
.PP 
A simple way to get all the necessary includes. 


.PP
Definition in file \fBcommon.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
