.TH "complex.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
complex.h \- Complex number definitions. 
.SH SYNOPSIS
.br
.PP
\fC#include <datatypes.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_COMPLEX\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBc_re\fP(x)   ((x).re)"
.br
.ti -1c
.RI "#define \fBc_im\fP(x)   ((x).im)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fB_COMPLEX\fP \fBCOMPLEX\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Complex number definitions. 

This file is part of a program that implements a Software-Defined Radio.
.PP
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
The authors can be reached by email at
.PP
\fBAuthor:\fP
.RS 4
ab2kt@arrl.net or 
.PP
rwmcgwier@comcast.net
.RE
.PP
or by paper mail at
.PP
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807 
.PP
Definition in file \fBcomplex.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define c_im(x)   ((x).im)"
.PP
Get imaginary part of complex number \fIx\fP 
.PP
Definition at line 52 of file complex.h.
.PP
Referenced by Cadd(), Cdiv(), Cmul(), Cscl(), and Csub().
.SS "#define c_re(x)   ((x).re)"
.PP
Get real part of complex number \fIx\fP 
.PP
Definition at line 49 of file complex.h.
.PP
Referenced by Cadd(), Cdiv(), Cmul(), Cscl(), and Csub().
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fB_COMPLEX\fP  \fBCOMPLEX\fP"
.PP
Complex number pseudo-type 
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
