.TH "correctIQ.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
correctIQ.h \- I/Q adjustment/calibration structures. 
.SH SYNOPSIS
.br
.PP
\fC#include <fromsys.h>\fP
.br
\fC#include <defs.h>\fP
.br
\fC#include <banal.h>\fP
.br
\fC#include <splitfields.h>\fP
.br
\fC#include <datatypes.h>\fP
.br
\fC#include <bufvec.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_iqstate\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIQ\fP \fBnewCorrectIQ\fP (\fBREAL\fP phase, \fBREAL\fP gain)"
.br
.ti -1c
.RI "void \fBdelCorrectIQ\fP (\fBIQ\fP iq)"
.br
.ti -1c
.RI "void \fBcorrectIQ\fP (\fBCXB\fP sigbuf, \fBIQ\fP iq)"
.br
.in -1c
.SH "Detailed Description"
.PP 
I/Q adjustment/calibration structures. 

This file is part of a program that implements a Software-Defined Radio.
.PP
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
The authors can be reached by email at
.PP
\fBAuthor:\fP
.RS 4
ab2kt@arrl.net or 
.PP
rwmcgwier@comcast.net
.RE
.PP
or by paper mail at
.PP
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807 
.PP
Definition in file \fBcorrectIQ.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
