.TH "cxops.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxops.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <complex.h>\fP
.br
\fC#include <datatypes.h>\fP
.br
\fC#include <fastrig.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCscl\fP (\fBCOMPLEX\fP, \fBREAL\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCadd\fP (\fBCOMPLEX\fP, \fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCsub\fP (\fBCOMPLEX\fP, \fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCmul\fP (\fBCOMPLEX\fP, \fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCdiv\fP (\fBCOMPLEX\fP, \fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBREAL\fP \fBCmag\fP (\fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBREAL\fP \fBCappmag\fP (\fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBREAL\fP \fBCabs\fP (\fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBREAL\fP \fBCsqrmag\fP (\fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCmplx\fP (\fBREAL\fP, \fBIMAG\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBConjg\fP (\fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCexp\fP (\fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCp2r\fP (\fBCOMPLEX\fP)"
.br
.ti -1c
.RI "INLINE \fBCOMPLEX\fP \fBCr2p\fP (\fBCOMPLEX\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBCOMPLEX\fP \fBcxzero\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBcxone\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBcxJ\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBcxminusone\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP \fBcxminusJ\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is part of a program that implements a Software-Defined Radio.
.PP
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
The authors can be reached by email at
.PP
\fBAuthor:\fP
.RS 4
ab2kt@arrl.net or 
.PP
rwmcgwier@comcast.net
.RE
.PP
or by paper mail at
.PP
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807 
.PP
Definition in file \fBcxops.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
