.TH "datatypes.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
datatypes.h \- Local definitions and aliases for our data. 
.SH SYNOPSIS
.br
.PP
\fC#include <fromsys.h>\fP
.br
\fC#include <complex.h>\fP
.br
\fC#include <thunk.h>\fP
.br
\fC#include <banal.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBPRIVATE\fP   static"
.br
.ti -1c
.RI "#define \fBINLINE\fP   inline"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned int \fBBOOLEAN\fP"
.br
.ti -1c
.RI "typedef float \fBREAL\fP"
.br
.ti -1c
.RI "typedef float \fBIMAG\fP"
.br
.ti -1c
.RI "typedef short \fBSAMPLE_16t\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Local definitions and aliases for our data. 

This file is part of a program that implements a Software-Defined Radio.
.PP
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
The authors can be reached by email at
.PP
\fBAuthor:\fP
.RS 4
ab2kt@arrl.net or 
.PP
rwmcgwier@comcast.net
.RE
.PP
or by paper mail at
.PP
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807 
.PP
Definition in file \fBdatatypes.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define INLINE   inline"
.PP
Item is declared inline with source 
.PP
Definition at line 65 of file datatypes.h.
.SS "#define PRIVATE   static"
.PP
Item is local to compilation unit (file, function) 
.PP
Definition at line 59 of file datatypes.h.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned int \fBBOOLEAN\fP"
.PP
Boolean pseudo-type 
.PP
Definition at line 43 of file datatypes.h.
.SS "typedef float \fBIMAG\fP"
.PP
Shorthand for \fIfloat\fP 
.PP
Definition at line 49 of file datatypes.h.
.SS "typedef float \fBREAL\fP"
.PP
Shorthand for \fIfloat\fP 
.PP
Definition at line 46 of file datatypes.h.
.SS "typedef short \fBSAMPLE_16t\fP"
.PP
Shorthand for \fIshort\fP 
.PP
Definition at line 52 of file datatypes.h.
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
