.TH "dcblock.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dcblock.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <fromsys.h>\fP
.br
\fC#include <defs.h>\fP
.br
\fC#include <banal.h>\fP
.br
\fC#include <splitfields.h>\fP
.br
\fC#include <datatypes.h>\fP
.br
\fC#include <bufvec.h>\fP
.br
\fC#include <cxops.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_dcblocker\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBLKMEM\fP   (9)"
.br
.ti -1c
.RI "#define \fBDCB_LOW\fP   (0)"
.br
.ti -1c
.RI "#define \fBDCB_MED\fP   (1)"
.br
.ti -1c
.RI "#define \fBDCB_HIGH\fP   (2)"
.br
.ti -1c
.RI "#define \fBDCB_SUPER\fP   (3)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBDCBlock\fP (\fBDCBlocker\fP dcb)"
.br
.ti -1c
.RI "void \fBresetDCBlocker\fP (\fBDCBlocker\fP dcb, int lev)"
.br
.ti -1c
.RI "\fBDCBlocker\fP \fBnewDCBlocker\fP (int lev, \fBCXB\fP buf)"
.br
.ti -1c
.RI "void \fBdelDCBlocker\fP (\fBDCBlocker\fP dcb)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file is part of a program that implements a Software-Defined Radio.
.PP
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
The authors can be reached by email at
.PP
\fBAuthor:\fP
.RS 4
ab2kt@arrl.net or 
.PP
rwmcgwier@comcast.net
.RE
.PP
or by paper mail at
.PP
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807 
.PP
Definition in file \fBdcblock.h\fP.
.SH "Define Documentation"
.PP 
.SS "#define BLKMEM   (9)"
.PP
\fITBD\fP 
.PP
Definition at line 46 of file dcblock.h.
.PP
Referenced by resetDCBlocker().
.SS "#define DCB_HIGH   (2)"
.PP
\fITBD\fP 
.PP
Definition at line 52 of file dcblock.h.
.PP
Referenced by DCBlock().
.SS "#define DCB_LOW   (0)"
.PP
\fITBD\fP 
.PP
Definition at line 48 of file dcblock.h.
.PP
Referenced by DCBlock().
.SS "#define DCB_MED   (1)"
.PP
\fITBD\fP 
.PP
Definition at line 50 of file dcblock.h.
.PP
Referenced by DCBlock(), and setup_tx().
.SS "#define DCB_SUPER   (3)"
.PP
\fITBD\fP 
.PP
Definition at line 54 of file dcblock.h.
.PP
Referenced by DCBlock().
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
