.TH "fromsys.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fromsys.h \- Stuff we need to import everywhere. 
.SH SYNOPSIS
.br
.PP
\fC#include <sys/types.h>\fP
.br
\fC#include <sys/param.h>\fP
.br
\fC#include <sys/stat.h>\fP
.br
\fC#include <sys/time.h>\fP
.br
\fC#include <sys/wait.h>\fP
.br
\fC#include <sys/mman.h>\fP
.br
\fC#include <sys/ioctl.h>\fP
.br
\fC#include <sys/socket.h>\fP
.br
\fC#include <signal.h>\fP
.br
\fC#include <time.h>\fP
.br
\fC#include <fcntl.h>\fP
.br
\fC#include <pthread.h>\fP
.br
\fC#include <semaphore.h>\fP
.br
\fC#include <unistd.h>\fP
.br
\fC#include <stdlib.h>\fP
.br
\fC#include <stdio.h>\fP
.br
\fC#include <ctype.h>\fP
.br
\fC#include <string.h>\fP
.br
\fC#include <math.h>\fP
.br
\fC#include <getopt.h>\fP
.br
\fC#include <jack/jack.h>\fP
.br
\fC#include <jack/ringbuffer.h>\fP
.br
\fC#include <assert.h>\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBM_PI\fP   3.14159265358928"
.br
.ti -1c
.RI "#define \fBMAXPATHLEN\fP   (2048)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stuff we need to import everywhere. 

This file is part of a program that implements a Software-Defined Radio.
.PP
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
The authors can be reached by email at
.PP
\fBAuthor:\fP
.RS 4
ab2kt@arrl.net or 
.PP
rwmcgwier@comcast.net
.RE
.PP
or by paper mail at
.PP
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807 
.PP
Definition in file \fBfromsys.h\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
