.TH "local.h" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
local.h \- Some manifest constants for the particular implementation. 
.SH SYNOPSIS
.br
.PP
\fC#include <common.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fB_loc\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBRCBASE\fP   '.DttSPrc'"
.br
.ti -1c
.RI "#define \fBPARMPATH\fP   '/dev/shm/SDRcommands'"
.br
.ti -1c
.RI "#define \fBMETERPATH\fP   '/dev/shm/SDRmeter'"
.br
.ti -1c
.RI "#define \fBREPLAYPATH\fP   '.replay'"
.br
.ti -1c
.RI "#define \fBSPECPATH\fP   '/dev/shm/SDRspectrum'"
.br
.ti -1c
.RI "#define \fBWISDOMPATH\fP   '.wisdom'"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fB_loc\fP \fBloc\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Some manifest constants for the particular implementation. 

This file is part of a program that implements a Software-Defined Radio.
.PP
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
.PP
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
.PP
The authors can be reached by email at
.PP
\fBAuthor:\fP
.RS 4
ab2kt@arrl.net or 
.PP
rwmcgwier@comcast.net
.RE
.PP
or by paper mail at
.PP
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807 
.PP
Definition in file \fBlocal.h\fP.
.SH "Variable Documentation"
.PP 
.SS "struct \fB_loc\fP  \fBloc\fP"
.PP
?? structure 
.PP
Referenced by execute(), reset_for_buflen(), setup(), setup_defaults(), setup_from_commandline(), setup_local_audio(), setup_system_audio(), and setup_updates().
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
