.TH "resample_state" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
resample_state \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBCOMPLEX\fP * \fBinput\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBoutput\fP"
.br
.ti -1c
.RI "\fBCOMPLEX\fP * \fBfilterMemoryBuff\fP"
.br
.ti -1c
.RI "\fBRealFIR\fP \fBfilter\fP"
.br
.ti -1c
.RI "int \fBfilterMemoryBuffLength\fP"
.br
.ti -1c
.RI "int \fBinputArrayLength\fP"
.br
.ti -1c
.RI "int \fBnumFiltTaps\fP"
.br
.ti -1c
.RI "int \fBindexfiltMemBuf\fP"
.br
.ti -1c
.RI "int \fBinterpFactor\fP"
.br
.ti -1c
.RI "int \fBfilterPhaseNum\fP"
.br
.ti -1c
.RI "int \fBdeciFactor\fP"
.br
.ti -1c
.RI "int \fBnumOutputSamples\fP"
.br
.ti -1c
.RI "int \fBmask\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file resample.h.

.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
