sdr-main.c
NAME
sdr-main.c - DttSp Mainline.
SYNOPSIS
#include <common.h>
Functions
void reset_meters (void)
void reset_spectrum (void)
void reset_counters (void)
void process_samples (float *, float *, int)
void setup_workspace (REAL rate, int buflen, SDRMODE mode, char *wisdom, int specsize, int numrecv, int cpdsize)
void destroy_workspace (void)
int reset_for_buflen (int new_buflen)
PRIVATE void spectrum_thread (void)
PRIVATE void meter_thread (void)
PRIVATE void monitor_thread (void)
PRIVATE void process_updates_thread (void)
PRIVATE void gethold (void)
PRIVATE BOOLEAN canhold (void)
PRIVATE void run_mute (void)
PRIVATE void run_pass (void)
PRIVATE void run_play (void)
PRIVATE void run_swch (void)
PRIVATE void audio_callback (jack_nframes_t nframes, void *arg)
PRIVATE void process_samples_thread (void)
PRIVATE void execute (void)
PRIVATE void setup_local_audio (void)
PRIVATE void setup_updates (void)
PRIVATE void jack_xrun (void *arg)
PRIVATE void jack_shutdown (void *arg)
PRIVATE void setup_system_audio (void)
PRIVATE sem_t * make_sem (char *id)
PRIVATE void setup_threading (void)
PRIVATE void setup_defaults (void)
PRIVATE void destroy_globals (void)
PRIVATE void closeup (void)
PRIVATE void usage (void)
PRIVATE void setup_from_commandline (int argc, char **argv)
PRIVATE void create_globals (void)
PRIVATE void setup (int argc, char **argv)
int main (int argc, char **argv)
Variables
_loc loc
PRIVATE struct option long_options []
PRIVATE char * short_options = 'vmsl:h?'
PRIVATE int option_index
Detailed Description
DttSp Mainline.
This file is part of a program that implements a Software-Defined Radio.
Copyright (C) 2004, 2005, 2006 by Frank Brickle, AB2KT and Bob McGwier, N4HY
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
You should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
The authors can be reached by email at
Author:
ab2kt@arrl.net or
rwmcgwier@comcast.net
or by paper mail at
The DTTS Microwave Society 6 Kathleen Place Bridgewater, NJ 08807
Definition in file sdr-main.c.
Function Documentation
PRIVATE void create_globals (void)
Allocate global memory areas
Definition at line 924 of file sdr-main.c.
References MAXRX, rx, safealloc(), top, tx, and uni.
Referenced by setup().
int main (int argc, char ** argv)
Mainline
Definition at line 979 of file sdr-main.c.
References closeup(), execute(), and setup().
PRIVATE void setup (int argc, char ** argv)
Set everything up
Definition at line 939 of file sdr-main.c.
References _loc::comp, create_globals(), _loc::def, DEFOFFS, DEFSIZE, _top::doin, FALSE, loc, _loc::mode, _loc::nrx, _top::offs, _loc::path, _top::pid, _loc::rate, reset_counters(), reset_meters(), reset_spectrum(), _top::rsiz, RUN_PLAY, _top::running, safememreset(), setup_defaults(), setup_from_commandline(), setup_local_audio(), setup_system_audio(), setup_threading(), setup_updates(), setup_workspace(), _loc::size, _top::snds, _loc::spec, _top::start_tv, _top::state, top, TRUE, _top::uid, _top::verbose, and _loc::wisdom.
Referenced by main().
PRIVATE void setup_defaults (void)
Setup default parameters
Definition at line 661 of file sdr-main.c.
References _loc::blowr, _loc::comp, _loc::def, DEFCOMP, DEFMODE, DEFOFFS, DEFRATE, DEFSIZE, DEFSPEC, _loc::echo, loc, MAXRX, _loc::meter, METERPATH, _loc::mode, _loc::mult, _loc::name, _loc::nrx, _loc::offs, _loc::parm, PARMPATH, _loc::path, _loc::rate, RCBASE, _loc::rcfile, _loc::replay, REPLAYPATH, _loc::ring, RINGMULT, _loc::size, _loc::skew, _loc::spec, SPECPATH, _loc::wisdom, and WISDOMPATH.
Referenced by setup().
PRIVATE void setup_from_commandline (int argc, char ** argv)
Setup based on command line arguments
Definition at line 831 of file sdr-main.c.
References _loc::blowr, _loc::def, _loc::echo, _meter_block::flag, _spec_block::flag, loc, _loc::meter, _uni::meter, _loc::mode, _loc::mult, _loc::name, _loc::offs, _loc::parm, _loc::path, _loc::rcfile, _loc::replay, _loc::ring, _loc::size, _loc::skew, _loc::spec, _uni::spec, top, TRUE, uni, usage(), _top::verbose, and _loc::wisdom.
Referenced by setup().
PRIVATE void usage (void)
Print out user help
Definition at line 985 of file sdr-main.c.
Referenced by setup_from_commandline().
Author
Generated automatically by Doxygen for DttSp from the source code.