.TH "thunk.c" 3 "5 Apr 2007" "Version 93" "DttSp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
thunk.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <common.h>\fP
.br
\fC#include <thunk.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "PRIVATE \fBBOOLEAN\fP \fBstreq\fP (char *p, char *q)"
.br
.ti -1c
.RI "Thunk \fBThunk_lookup\fP (\fBCTB\fP ctb, char *key)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition in file \fBthunk.c\fP.
.SH "Author"
.PP 
Generated automatically by Doxygen for DttSp from the source code.
